= gitbucket-asciidoctor-plugin
:plugin-version: 0.1.0

image:https://travis-ci.org/lefou/gitbucket-asciidoctor-plugin.svg["Build Status", link="https://travis-ci.org/lefou/gitbucket-asciidoctor-plugin"]

A https://github.com/takezoe/gitbucket[GitBucket] plug-in that provides AsciiDoc rendering capabilities.
All `.adoc` (and also the deprecated `.asciidoc` and `.ad` suffix) files will be automatically rendered as AsciiDoc, supporting most features of the http://asciidoctor.org/[Asciidoctor project], including rendering of a table of contents.

== Download

You can download a precompiled version from the https://github.com/lefou/gitbucket-asciidoctor-plugin/releases[Release page].

== Build from source

----
sbt clean package
----

The built package is located at `target/scala-2.11/gitbucket-asciidoctor-plugin-{plugin-version}.jar`.

== Installation

Download `gitbucket-asciidoctor-plugin-{plugin-version}.jar` or build the JAR file from source and copy it into `GITBUCKET_HOME/plugins`. Then restart GitBucket. That's it.

== License

This plugin is published under the Apache License, version 2.0.

== ChangeLog

=== gitbucket-asciidoctor-plugin 0.1.0 - 2015-10-06

* Initial release
